[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/skratchdot/open-golang"

[[constraint]]
  branch = "master"
  name = "github.com/vaughan0/go-ini"

[prune]
  go-tests = true
  unused-packages = true
